//
// Formato Generacion Dinamica de Elementos HTML
//

// id: indice en la tabla
// panel: contenedor visual. [1,2,3] en este caso
// level: tiene o no tiene subpanel. [0:no , 1:si]
// type: disposicion del elemento en panel/level
//
const dataTable = [
  {
    id: 1,
    flw_button: "101",
    panel: "1",
    level: 0,
    type: "top1",
    classNam: "inactive",
    buttName: "BTN-1",
    buttSize: "95%",
    buttonStatus: "inactive",
  },
  {
    id: 2,
    flw_button: "102",
    panel: "1",
    level: 1,
    type: "top1",
    classNam: "inactive",
    buttName: "BTN-1",
    buttSize: "95%",
    buttonStatus: "inactive",
  },
  {
    id: 103,
    flw_button: "103",
    panel: "1",
    level: 1,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-2",
    buttSize: "29%",
    buttonStatus: "inactive",
  },
  {
    id: 104,
    flw_button: "104",
    panel: "1",
    level: 1,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-3",
    buttSize: "29%",
    buttonStatus: "inactive",
  },
  {
    id: 105,
    flw_button: "105",
    panel: "1",
    level: 1,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-4",
    buttSize: "29%",
    buttonStatus: "inactive",
  },
  {
    id: 106,
    flw_button: "106",
    panel: "1",
    level: 0,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-1",
    buttSize: "95%",
    buttonStatus: "inactive",
  },

  //---- 2 ----------------------------------------------------------------------
  {
    id: 201,
    flw_button: "201",
    panel: "2",
    level: 2,
    type: "top1",
    classNam: "inactive",
    buttName: "BTN-1",
    buttSize: "96%",
    buttonStatus: "inactive",
  },
  {
    id: 202,
    flw_button: "202",
    panel: "2",
    level: 2,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-2",
    buttSize: "47%",
    buttonStatus: "inactive",
  },
  {
    id: 203,
    flw_button: "203",
    panel: "2",
    level: 2,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-3",
    buttSize: "47%",
    buttonStatus: "inactive",
  },
  {
    id: 204,
    flw_button: "204",
    panel: "2",
    level: 2,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-2",
    buttSize: "47%",
    buttonStatus: "inactive",
  },
  {
    id: 205,
    flw_button: "205",
    panel: "2",
    level: 2,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-3",
    buttSize: "47%",
    buttonStatus: "inactive",
  },
  {
    id: 207,
    flw_button: "207",
    panel: "2",
    level: 3,
    type: "top1",
    classNam: "inactive",
    buttName: "BTN-1",
    buttSize: "96%",
    buttonStatus: "inactive",
  },
  {
    id: 208,
    flw_button: "208",
    panel: "2",
    level: 3,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-3",
    buttSize: "12%",
    buttonStatus: "inactive",
  },
  {
    id: 209,
    flw_button: "209",
    panel: "2",
    level: 3,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-3",
    buttSize: "12%",
    buttonStatus: "inactive",
  },
  {
    id: 210,
    flw_button: "210",
    panel: "2",
    level: 3,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-3",
    buttSize: "12%",
    buttonStatus: "inactive",
  },
  {
    id: 211,
    flw_button: "211",
    panel: "2",
    level: 3,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-3",
    buttSize: "12%",
    buttonStatus: "inactive",
  },
  {
    id: 212,
    flw_button: "212",
    panel: "2",
    level: 3,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-3",
    buttSize: "12%",
    buttonStatus: "inactive",
  },
  {
    id: 213,
    flw_button: "213",
    panel: "2",
    level: 3,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-3",
    buttSize: "12%",
    buttonStatus: "inactive",
  },
  {
    id: 214,
    flw_button: "214",
    panel: "2",
    level: 3,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-3",
    buttSize: "12.5%",
    buttonStatus: "inactive",
  },
  {
    id: 215,
    flw_button: "215",
    panel: "2",
    level: 4,
    type: "top1",
    classNam: "inactive",
    buttName: "BTN-1",
    buttSize: "96%",
    buttonStatus: "inactive",
  },
  {
    id: 216,
    flw_button: "216",
    panel: "2",
    level: 4,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-3",
    buttSize: "58%",
    buttonStatus: "inactive",
  },
  {
    id: 217,
    flw_button: "217",
    panel: "2",
    level: 4,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-3",
    buttSize: "36%",
    buttonStatus: "inactive",
  },
  {
    id: 218,
    flw_button: "218",
    panel: "2",
    level: 4,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-3",
    buttSize: "13%",
    buttonStatus: "inactive",
  },
  {
    id: 219,
    flw_button: "219",
    panel: "2",
    level: 4,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-3",
    buttSize: "13%",
    buttonStatus: "inactive",
  },
  {
    id: 220,
    flw_button: "220",
    panel: "2",
    level: 4,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-3",
    buttSize: "13.5%",
    buttonStatus: "inactive",
  },
  {
    id: 221,
    flw_button: "221",
    panel: "2",
    level: 4,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-3",
    buttSize: "13%",
    buttonStatus: "inactive",
  },
  {
    id: 222,
    flw_button: "222",
    panel: "2",
    level: 4,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-3",
    buttSize: "10%",
    buttonStatus: "inactive",
  },
  {
    id: 223,
    flw_button: "223",
    panel: "2",
    level: 4,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-3",
    buttSize: "12%",
    buttonStatus: "inactive",
  },
  {
    id: 224,
    flw_button: "224",
    panel: "2",
    level: 4,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-3",
    buttSize: "10%",
    buttonStatus: "inactive",
  },

  {
    id: 225,
    flw_button: "225",
    panel: "2",
    level: 3,
    type: "top1",
    classNam: "inactive",
    buttName: "BTN-1",
    buttSize: "96%",
    buttonStatus: "inactive",
  },
  {
    id: 226,
    flw_button: "226",
    panel: "2",
    level: 3,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-3",
    buttSize: "14%",
    buttonStatus: "inactive",
  },
  {
    id: 227,
    flw_button: "227",
    panel: "2",
    level: 3,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-3",
    buttSize: "14%",
    buttonStatus: "inactive",
  },
  {
    id: 228,
    flw_button: "228",
    panel: "2",
    level: 3,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-3",
    buttSize: "14%",
    buttonStatus: "inactive",
  },
  {
    id: 229,
    flw_button: "229",
    panel: "2",
    level: 3,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-3",
    buttSize: "14%",
    buttonStatus: "inactive",
  },
  {
    id: 230,
    flw_button: "230",
    panel: "2",
    level: 3,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-3",
    buttSize: "14%",
    buttonStatus: "inactive",
  },
  {
    id: 231,
    flw_button: "231",
    panel: "2",
    level: 3,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-3",
    buttSize: "16.5%",
    buttonStatus: "inactive",
  },

  {
    id: 232,
    flw_button: "232",
    panel: "2",
    level: 0,
    type: "top1",
    classNam: "inactive",
    buttName: "BTN-1",
    buttSize: "96%",
    buttonStatus: "inactive",
  },
  {
    id: 233,
    flw_button: "233",
    panel: "2",
    level: 1,
    type: "top1",
    classNam: "inactive",
    buttName: "BTN-1",
    buttSize: "96%",
    buttonStatus: "inactive",
  },

  //---- 3 ----------------------------------------------------------------------
  {
    id: 301,
    flw_button: "301",
    panel: "3",
    level: 1,
    type: "top1",
    classNam: "inactive",
    buttName: "BTN-1",
    buttSize: "95%",
    buttonStatus: "inactive",
  },
  {
    id: 302,
    flw_button: "302",
    panel: "3",
    level: 1,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-2",
    buttSize: "29%",
    buttonStatus: "inactive",
  },
  {
    id: 303,
    flw_button: "303",
    panel: "3",
    level: 1,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-3",
    buttSize: "29%",
    buttonStatus: "inactive",
  },
  {
    id: 304,
    flw_button: "304",
    panel: "3",
    level: 1,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-3",
    buttSize: "29%",
    buttonStatus: "inactive",
  },
  {
    id: 305,
    flw_button: "305",
    panel: "3",
    level: 0,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-3",
    buttSize: "95%",
    buttonStatus: "inactive",
  },
  {
    id: 306,
    flw_button: "306",
    panel: "3",
    level: 1,
    type: "top2",
    classNam: "inactive",
    buttName: "BTN-3",
    buttSize: "95%",
    buttonStatus: "disabled",
  },
  {
    id: 307,
    flw_button: "307",
    panel: "3",
    level: 1,
    type: "top3",
    classNam: "inactive",
    buttName: "BTN-3",
    buttSize: "22%",
    buttonStatus: "disabled",
  },
  {
    id: 308,
    flw_button: "308",
    panel: "3",
    level: 1,
    type: "top3",
    classNam: "inactive",
    buttName: "BTN-3",
    buttSize: "22%",
    buttonStatus: "disabled",
  },
  {
    id: 309,
    flw_button: "309",
    panel: "3",
    level: 1,
    type: "top3",
    classNam: "inactive",
    buttName: "BTN-3",
    buttSize: "22%",
    buttonStatus: "disabled",
  },
  {
    id: 310,
    flw_button: "310",
    panel: "3",
    level: 1,
    type: "top3",
    classNam: "inactive",
    buttName: "BTN-3",
    buttSize: "22%",
    buttonStatus: "disabled",
  },
];
//------------------------------------------------------------------------
//

export default dataTable;
